language: python
env: 
    global: 
    - CC_TEST_REPORTER_ID=514102ba948d6b71efaeb23f0931f6be0fee4fd02a78006b483a5934753d836e

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

python:
- "3.7.4"

install:
- curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
- python get-pip.py
- pip install pytest

script:
- pytest

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
